services:
  - type: web
    name: uznpuu-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    disk:
      name: db
      mountPath: /app/data
      sizeGB: 1
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
